### ISSUE TITLE
assignment to nil entry upon registering for a room that does not exist

### ISSUE THREAD

**Issue by oxytocin** [mike2ykme/FCC-Dallas-cohort-C#17]
Discovered this bug on the develop branch. To replicate this, send a request to `ws://[backend host url]/ws/[any room id that doesn't exist]`. Server crashes with output like

```
2022/06/09 16:49:08 there is no room with key: 24a00ff0-8d6d-4518-916a-99230fe98de3
panic: assignment to entry in nil map

goroutine 9 [running]:
teamC/web.handleRegistration(0xc000296340)
        /Users/Joesaccount/Documents/coding_for_fun/cohort/FCC-Dallas-cohort-C/web/connectionHub.go:37 +0x265
teamC/web.RunHub()
        /Users/Joesaccount/Documents/coding_for_fun/cohort/FCC-Dallas-cohort-C/web/connectionHub.go:196 +0x154
created by main.main
        /Users/Joesaccount/Documents/coding_for_fun/cohort/FCC-Dallas-cohort-C/web/cmd/main.go:50 +0x1ff
exit status 2
```

Presumably, this is because `entry` gets assigned to `nil` on line 27. Maybe `handleRegistration` should just return early if the key doesn't exist?

**Comment by mike2ykme** [comment]
I should do a better return to user, but this is somewhat expected behavior. Just need to check and not cause an error and instead refuse connections on non setup rooms

**Comment by mike2ykme** [comment]
Exception comes from trying to connect to a room that's not in a good state, any room that has been previously closed won't be active anymore and now will just reject connections.
